### ISSUE TITLE
気になるところ。

### ISSUE THREAD

**Issue by watap7** [vuejs-jp/handson-vue3#65]
- [x] VS Code の略称: #66 
- [ ] Vue CLI の表示: #71 
- [ ] methods へのリンク修正: #72 
- [ ] `v-for` と `v-if` のタグ修正: #73

overview.md　>  ## 作成の流れ ← ## 目次　でもいいのかなと思いました。

**Comment by k-miyake** [comment]
@watap7 ご指摘ありがとうございした。

> overview.md　> ## 作成の流れ ← ## 目次　でもいいのかなと思いました。　　

目次はトップページに作成したので、ここはこのまま「作成の流れ」にしたいと思います。

> ハンズオンの概要（本ページ）からの順がいいのではないでしょうか？

全体の目次と合わせたいので、このままでいかせてください。

> setup.md > ## Node.js のインストール...

M1 Mac での動作確認ありがとうございます。ハンズオン中に同じ環境の方がいた場合は参考にさせていただこうと思います。

> setup.md > Visual Studio Code (以下、VSCode) ...

#66 にて修正しましたので、レビューお願いします。

**Comment by watap7** [comment]
create.md > vue create vue3-lab 実行後 > 

vue create vue3-lab

実行後のプロンプト Please pick a preset では、このワークショップでは以下のように Default (Vue 3 Preview) を選択します。

プロンプト内では、矢印キーで移動、Space キーで選択、Enter キーで確定ができます

? Please pick a preset:
  Default ([Vue 2] babel, eslint)
  ❯ Default (Vue 3 Preview) ([Vue 3] babel, eslint)
  Manually select features
次のプロンプト Pick the package manager to use when installing dependencies: では、好みのパッケージマネージャーを選んでください。（このハンズオンでは、npm を前提に説明を進めますので、適宜読み替えてください）

? Pick the package manager to use when installing dependencies:
Use Yarn
❯ Use NPM

Vue CLI v4.5.13　だと文言が違う。しょうがないっすね。こればっかりは。

% vue create vue3-lab

Vue CLI v4.5.13
? Please pick a preset: 
  Default ([Vue 2] babel, eslint) 
❯ Default (Vue 3) ([Vue 3] babel, eslint) 
  Manually select features 

選択すると、以下の文がなく、CLIのインストールが始まります。

? Pick the package manager to use when installing dependencies:
Use Yarn
❯ Use NPM

**Comment by k-miyake** [comment]
@watap7 Vue CLI は最新にした方が受講者の画面と合うので、#71 で対応させていただきました。フィードバックありがとうございました。

**Comment by watap7** [comment]
v-for.md >

**Comment by watap7** [comment]
overview.md. > 作成の流れに

methods.md  ファイルの読み込みがない。

- [methods で価格にカンマを入れる](./v-if.md "methods で価格にカンマを入れる")  

./v-if.md ではなく。./methods.md ではないでしょうか？

**Comment by watap7** [comment]
README.md

同様に、

1. [methods で価格にカンマを入れる](./v-if.md 'methods で価格にカンマを入れる')

↓

1. [methods で価格にカンマを入れる](./methods.md 'methods で価格にカンマを入れる')

**Comment by k-miyake** [comment]
@watap7  リンク先のミス、#72 で修正しました。ありがとうございます。

**Comment by watap7** [comment]
v-for.md  から、 v-if.md の教材で、itemsを追加するんですが、

```
        {
          id: 4,
          name: 'チーズフレンチフライ',
          description:
            'イタリア産チーズをたっぷりかけたアツアツのフレンチフライ。みんな大好きな一品です。',
          price: 670,
          image: '/images/item4.jpg'
        }
```
から、そのあとに、
```
          {
            id: 5,
            name: '商品５',
            description: '商品５の説明です',
            price: 500,
            selected: false,
            // 売り切れかどうかを判断するプロパティーを追加
            soldOut: true
          }
```
を追加するんですが、` },{`  v-if.md  ファイルの方に、 `,` が欲しいかもです。

**Comment by watap7** [comment]
v-if.md >  ### DOM 要素に v-if を追加

次に、DOM 要素に `v-if` を追加して、非表示にします。
1 つ 1 つの商品を表示している要素は以下の部分です。

したのソース

```html
<template>
  <!-- 省略 -->
  <main class="main">
    <template v-for="item in items" :key="item.id">
      <!-- ここから商品表示 -->
      <div class="item">
        <div class="thumbnail">
          <img :src="item.image" alt="" />
        </div>
        <div class="description">
          <h2>{{ item.name }}</h2>
          <p>{{ item.description }}</p>
          <span>￥<span class="price">item.price</span></span>
        </div>
      </div>
    </template>
  </main>
</template>
```
の　以下の部分
```
        </div>
      </div>
    </template>
  </main>
</template>
```

`</template>` の 閉じたぐが二つあるのと。多分、この部分にv-for.md で指摘した、代わりに</div>タグを入れるんだと思います。

**Comment by k-miyake** [comment]
@watap7 `v-for` と `v-if` 関連の指摘事項を #73 で対応しました。
すみません、まだ追加があればタスク管理が難しくなるので、Issue の概要欄で `- [ ]` 形式のサブタスクにしていただくか、別 Issue を作成して下さい。
